### ISSUE TITLE
Noto Sans Syriac does not build

### ISSUE THREAD

**Issue by madig** [googlefonts/noto-fonts#1586]
### Noto Sans Syriac does not build from master

1. Clone Git master (commit `933987e2509b9ae5192420a8296f330c25df7652`)
2. `./build setup`
3. `./build src/NotoSansSyriac/NotoSansSyriac-MM.plist`

Log:

```
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "src/NotoSansSyriac/NotoSansSyriac-MM.glyphs" file into <GSFont>
INFO:fontmake.font_project:Building OTF for NotoSansSyriac-Thin
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on NotoSansSyriac-Thin
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on NotoSansSyriac-Thin
INFO:ufo2ft:Building OpenType tables
INFO:ufo2ft.postProcessor:Subroutinizing CFF table
INFO:fontmake.font_project:Saving master_otf/NotoSansSyriac-Thin.otf
INFO:fontmake.font_project:Building OTF for NotoSansSyriac-Regular
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on NotoSansSyriac-Regular
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on NotoSansSyriac-Regular
INFO:ufo2ft:Building OpenType tables
INFO:ufo2ft.postProcessor:Subroutinizing CFF table
INFO:fontmake.font_project:Saving master_otf/NotoSansSyriac-Regular.otf
INFO:fontmake.font_project:Building OTF for NotoSansSyriac-Black
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on NotoSansSyriac-Black
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on NotoSansSyriac-Black
INFO:ufo2ft:Building OpenType tables
INFO:ufo2ft.postProcessor:Subroutinizing CFF table
INFO:fontmake.font_project:Saving master_otf/NotoSansSyriac-Black.otf
INFO:fontmake.font_project:Building TTF for NotoSansSyriac-Thin
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on NotoSansSyriac-Thin
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on NotoSansSyriac-Thin
INFO:ufo2ft.filters:Running CubicToQuadraticFilter on NotoSansSyriac-Thin
INFO:ufo2ft.filters.cubicToQuadratic:New spline lengths: 1: 530, 2: 5337, 3: 1008, 4: 182, 5: 53, 6: 13
INFO:ufo2ft:Building OpenType tables
INFO:fontmake.font_project:Saving master_ttf/NotoSansSyriac-Thin.ttf
INFO:fontmake.font_project:Building TTF for NotoSansSyriac-Regular
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on NotoSansSyriac-Regular
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on NotoSansSyriac-Regular
INFO:ufo2ft.filters:Running CubicToQuadraticFilter on NotoSansSyriac-Regular
INFO:ufo2ft.filters.cubicToQuadratic:New spline lengths: 1: 986, 2: 4913, 3: 930, 4: 175, 5: 19, 6: 13
INFO:ufo2ft:Building OpenType tables
INFO:fontmake.font_project:Saving master_ttf/NotoSansSyriac-Regular.ttf
INFO:fontmake.font_project:Building TTF for NotoSansSyriac-Black
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on NotoSansSyriac-Black
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on NotoSansSyriac-Black
INFO:ufo2ft.filters:Running CubicToQuadraticFilter on NotoSansSyriac-Black
INFO:ufo2ft.filters.cubicToQuadratic:New spline lengths: 1: 504, 2: 5264, 3: 1015, 4: 196, 5: 36, 6: 2
INFO:ufo2ft:Building OpenType tables
INFO:fontmake.font_project:Saving master_ttf/NotoSansSyriac-Black.ttf
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "src/NotoSansSyriac/NotoSansSyriac-MM.glyphs" file into <GSFont>
INFO:fontmake.font_project:Interpolating master UFOs from designspace and applying instance data
INFO:fontmake.font_project:Building OTF for NotoSansSyriac-Thin
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on NotoSansSyriac-Thin
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on NotoSansSyriac-Thin
INFO:ufo2ft:Building OpenType tables
INFO:ufo2ft.postProcessor:Subroutinizing CFF table
INFO:fontTools.varLib:Axes:
[{'default': 400.0,
  'hidden': False,
  'labelNames': {'en': 'Weight'},
  'map': [(100.0, 26.0), (400.0, 90.0), (900.0, 190.0)],
  'maximum': 900.0,
  'minimum': 100.0,
  'name': 'Weight',
  'tag': 'wght'}]
INFO:fontTools.varLib:Internal master locations:
[{'Weight': 26.0}, {'Weight': 90.0}, {'Weight': 190.0}]
INFO:fontTools.varLib:Internal axis supports:
{'Weight': [26.0, 90.0, 190.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'Weight': -1.0}, {'Weight': 0.0}, {'Weight': 1.0}]
INFO:fontTools.varLib:Index of base master: 1
INFO:fontTools.varLib.interpolate_layout:Building interpolated font
INFO:fontTools.varLib.interpolate_layout:Loading master fonts
INFO:fontTools.varLib.interpolate_layout:Location: {'Weight': 26.0}
INFO:fontTools.varLib.interpolate_layout:Internal location: {'Weight': 26.0}
INFO:fontTools.varLib.interpolate_layout:Normalized location: {'Weight': -1.0}
INFO:fontTools.varLib.interpolate_layout:Building interpolated tables
Traceback (most recent call last):
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/scripts/fontmake/Lib/fontmake/__main__.py", line 405, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/scripts/fontmake/Lib/fontmake/font_project.py", line 649, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/scripts/fontmake/Lib/fontmake/font_project.py", line 866, in run_from_designspace
    **kwargs,
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/scripts/fontmake/Lib/fontmake/font_project.py", line 929, in _run_from_designspace_static
    **kwargs,
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/scripts/fontmake/Lib/fontmake/font_project.py", line 990, in run_from_ufos
    self.build_otfs(ufos, **kwargs)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/scripts/fontmake/Lib/fontmake/font_project.py", line 197, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 374, in wrapper
    return func(*args, **kwds)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/scripts/fontmake/Lib/fontmake/font_project.py", line 469, in save_otfs
    interpolate_layout_from, loc, finder, mapped=True
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/varLib/interpolate_layout.py", line 56, in interpolate_layout
    merger.mergeTables(font, master_fonts, ['GPOS'])
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 109, in mergeTables
    for m in master_ttfs])
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeObjects(out, lst)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeObjects(out, lst)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeObjects(out, lst)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 97, in mergeThings
    self.mergeLists(out, lst)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 83, in mergeLists
    self.mergeThings(value, values)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeObjects(out, lst)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeObjects(out, lst)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/mnt/c/UsersLocal/nikolaus.waxweiler/Development/noto-source/env/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 99, in mergeThings
    assert allEqualTo(out, lst), (out, lst)
AssertionError: ((26, [26, 26, 27]), 'int', '.LookupCount', 'Feature', '.Feature', 'FeatureRecord', '[0]', 'list', '.FeatureRecord', 'FeatureList', '.FeatureList', 'GPOS', '.table', 'table_G_P_O_S_')
```

This seems to be about some lookup for one font having one more item than the others.

**Comment by punchcutter** [comment]
Interesting since it used to build. The source files should be the same as before and only fontmake should be different. This seems like the same old problem with GPOS we've had a million times where the binary compilation optimizes the lookups differently for each weight. I explained it elsewhere, but basically the GPOS is compatible and then compilation changes the structure so that the binaries are no longer compatible. I assume it's because something (probably relatively minor) changed at some point in the fontmake pipeline regarding some kind of GPOS lookup type.

**Comment by anthrotype** [comment]
I'll take a look. But isn't Syriac one of the sources which has MTI features (with .plist)? Fontmake doesn't build any automatic features for those, only what's in the MTI feature files

**Comment by punchcutter** [comment]
Oh, I should have paid attention. You can't run `build` on this file. It's not interpolatable. It never was. It's a special case, but I guess we somehow missed it in the noto-source build file. Nastaliq is in there as an exception, but Syriac also can't be interpolated. You can run `fontmake` on it fine with something like `fontmake -g NotoSansSyriac-MM.glyphs --mti-source NotoSansSyriac-MM.plist --no-production-names` to generate the 3 weights, but that's it. The GPOS issue I mentioned above is a separate issue.

**Comment by simoncozens** [comment]
Noto Sans Syriac can now be build with fontmake. We have a source per master, and it cannot be interpolated into a variable font because the GPOS layout rules are substantially different; not just a matter of different numbers, but actually different rules. I'd like to make them compatible one day, but that won't happen for a while.
